Repository GrabBits/GrabBits_Website, pull requests merged in 2023-05, with the labels that each got.

#48 changing the UI of the navbar
  client/public/index.html
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/Navbar.module.css
Labels: enhancement, gssoc23, level2

#60 FAQ section is updated
  client/public/index.html
  client/src/components/Faq/Faq.css
  client/src/components/Faq/Faq.jsx
  client/src/components/Faq/Faq.module.css
  package-lock.json
Labels: enhancement, gssoc23, level3

#61 Refactoring "SERVER" folder structure.
  server/config.js
  server/controllers/mailer.js
  server/controllers/user.controller.js
  server/database/db.js
  server/index.js
  server/middleware/auth.js
  server/middleware/errorMiddleware.js
  server/package-lock.json
  server/utils/config.js
Labels: enhancement, gssoc23, Medium, level3

#70 Updated Who_We_Are Section
  client/src/components/About/About.module.css
Labels: enhancement, gssoc23, Easy, level1

#73 Updated "Contact Us" Section
  client/src/components/Faq/Faq.css
  client/src/components/common/Button/Button.module.css
Labels: gssoc23, Easy, level1

#79 Added mail link and hover effect
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.css
Labels: enhancement, gssoc23, Easy, level1

#96 #87-input tag fix
  client/src/components/Faq/Faq.css
  client/src/components/Faq/Faq.jsx
  package-lock.json
Labels: gssoc23, Easy, level1

#86 footer changes
  client/src/components/Footer/Footer.module.css
Labels: gssoc23, level2

#81 Adding Hover Effect
  client/src/components/Extra/Extra.jsx
  client/src/components/Extra/Extra.module.css
Labels: gssoc23, level1

#102 added tech stacks
  README.md
Labels: documentation, enhancement, gssoc23, level1

#98 handling tags dislocation
  client/src/components/Opportunities/Opportunities.jsx
  client/src/components/Opportunities/Opportunities.module.css
Labels: enhancement, gssoc23, level1
