Repository GrabBits/GrabBits_Website, pull requests merged in 2023-07, with the labels that each got.

#160 Feat : Error Page Added
  client/public/background.jpg
  client/src/components/PageNotFound/PageNotFound.css
  client/src/components/PageNotFound/PageNotFound.jsx
  client/src/components/PageNotFound/PageNotFound.module.css
Labels: enhancement, gssoc23, level2

#244 Overwriting removed on Podcast Page
  client/src/components/Podcast/Podcast.jsx
  client/src/components/Podcast/Podcast.module.css
Labels: gssoc23, level1

#242 feat: improve loader on opportunities page
  client/src/components/Opportunities/Opportunities.jsx
  client/src/components/Opportunities/Opportunities.module.css
  client/src/components/Opportunities/PreLoader/PreLoader.jsx
  client/src/components/Opportunities/PreLoader/PreLoader.module.css
  client/src/components/common/Loader/Loader.jsx
Labels: gssoc23, level2

#256 Current Podcast Cards Made even
  client/src/components/common/PodcastCard/PodcastCard.jsx
  client/src/components/common/PodcastCard/PodcastCard.module.css
Labels: gssoc23, level1
