Repository GrabBits/GrabBits_Website, pull requests merged in 2023-06, with the labels that each got.

#112 docs: Add Contributor Graph
  README.md
Labels: documentation, gssoc23, Easy, level1

#131 💡 [FEAT]: ACCESSIBILITY IMPROVEMENTS FOR SOCIAL ANCHORS ON FOOTER
  client/src/components/Footer/Footer.jsx
Labels: bug, gssoc23, level1

#139 Add Back To Top Button
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/GoToTop.js
Labels: enhancement, good first issue, gssoc23, level2

#150 [Fix]: content overflows out of container on mobile screen devices #125
  client/src/components/Extra/Extra.module.css
Labels: bug, gssoc23, level1

#166 [Bug] faq form fix
  client/src/components/Faq/Faq.jsx
Labels: bug, gssoc23, level1

#165 adding scroll-to-top feature in landing page
  client/src/components/Landing/Landing.jsx
Labels: bug, gssoc23, level1

#188 Added alt attributes
  client/src/components/Extra/Extra.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Landing/Landing.jsx
  client/src/components/Testimonials/Testimonial.jsx
  client/src/components/common/Ticket/Ticket.jsx
Labels: bug, good first issue, gssoc23, level1

#182 Lazy loading added
  client/src/App.css
  client/src/App.jsx
  client/src/components/index.js
  client/src/pages/index.js
Labels: gssoc23, level2

#193 Meta tags added
  client/public/index.html
Labels: gssoc23, level1

#201 pagination fixed
  client/src/components/Opportunities/Opportunities.jsx
  server/controllers/job.controller.js
Labels: gssoc23, level3

#222 Resolved search bug
  client/src/components/Opportunities/Opportunities.jsx
Labels: gssoc23, level3
