Repository GrabBits/GrabBits_Website, pull requests merged in 2023-08, with the labels that each got.

#273 Added Resource Page
  client/package-lock.json
  client/package.json
  client/public/Arrow_.png
  client/public/brainstorming.svg
  client/public/graduation.svg
  client/public/index.html
  client/public/right-arrow.png
  client/public/undraw_Graduation_re_gthn.png
  client/src/App.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Resources/Resources.jsx
  client/src/components/Resources/Resources.module.css
  client/src/components/index.js
Labels: enhancement, gssoc23, New feature, level3

#227 Added testimonial section
  client/package-lock.json
  client/package.json
  client/src/animation/motion.jsx
  client/src/components/Testimonials/Card.module.css
  client/src/components/Testimonials/CardData.js
  client/src/components/Testimonials/TeamPostCard.jsx
  client/src/components/Testimonials/Testimonial.jsx
  client/src/components/Testimonials/Testimonial.module.css
  client/src/components/Testimonials/wolf.jpg
  client/src/pages/Homepage.jsx
Labels: enhancement, gssoc23, New feature, level1

#285 Refactor Landing Page And Highlight Section And Ticket
  client/src/assets/Highlights/postman.png
  client/src/components/Highlights/Highlights.module.css
  client/src/components/Landing/Landing.jsx
  client/src/components/Landing/Landing.module.css
  client/src/components/common/Button/Button.jsx
  client/src/components/common/Ticket/Ticket.module.css
Labels: enhancement, gssoc23, level2

#288 close navbar on click and repositioned the close button
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/Navbar.module.css
Labels: enhancement, gssoc23, level2

#289 Made fixes in testimonial section and made navigation buttons working
  client/src/components/Testimonials/Card.module.css
  client/src/components/Testimonials/TeamPostCard.jsx
Labels: enhancement, gssoc23, level2

#291 fixed issue of navbar logo
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/Navbar.module.css
Labels: gssoc23, level2

#290 Made Changes In Homepage incliuding extra component and fixes
  client/src/components/Extra/Extra.jsx
  client/src/components/Extra/Extra.module.css
Labels: gssoc23, level2

#294 Dynamic title
  client/.env
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Resources/Resources.jsx
Labels: enhancement, gssoc23, New feature, level3
